### ISSUE TITLE
Solos: addDeposit() should check the consistency of _withdrawalCredentials

### ISSUE THREAD

**Issue by daejunpark** [stakewise/contracts#44]
An user can call addDeposit() multiple times, where he should use the same withdrawal credential for every call.

However, if the user makes a mistake and provides different withdrawal credentials for different calls, then currently addDeposit() _silently ignores_ them, overwriting them with the very first withdrawal credential used in the first call.

For usability perspective, it is safer to revert when the given withdrawal credential is different from the first one, so that users can be informed of their misuse.

**Comment by tsudmi** [comment]
The `withdrawalCredentials` are used as part of the `soloId` [here](https://github.com/stakewise/contracts/blob/master/contracts/collectors/Solos.sol#L79), so the user can't override the existing withdrawal credentials. The issue I could see here is that the user maybe wants to diversify the withdrawal credentials (for the safety?), but won't be able to submit the different ones.

**Comment by daejunpark** [comment]
Ah, you're right. I missed that. Sorry about that.
