### ISSUE TITLE
stETH + rwETH balance can be bigger than validators sum balance when penalties are rounded down

### ISSUE THREAD

**Issue by tsudmi** [stakewise/contracts#45]
subtract 1 Wei when `rewardPerToken.sub(cp.rewardPerToken) < 0`

**Comment by daejunpark** [comment]
Subtract 1 wei:

Not only for (when `rewardPerToken.sub(cp.rewardPerToken) < 0`):
https://github.com/stakewise/contracts/blob/df7224dc73339e0c3c4b3f87416362953af36d34/contracts/tokens/RewardEthToken.sol#L91

But also for (when `periodRewards < 0`):
https://github.com/stakewise/contracts/blob/df7224dc73339e0c3c4b3f87416362953af36d34/contracts/tokens/RewardEthToken.sol#L133
